<#
.SYNOPSIS
    Regenerates [generated] files in PayrollEngine.AiContext (OSS) from source repositories.

.DESCRIPTION
    Generates the MCP Server read-only tool inventory from McpServer/README.md.
    
    For Regulation context (Exchange schema, Scripting API, No-Code actions),
    see Generate-AiContext.Pro.ps1 in PayrollEngine.AiContext.Pro.

.PARAMETER ReposRoot
    Root directory containing all PE repositories.
    Default: C:\Shared\PayrollEngine\Repos

.EXAMPLE
    .\Generate-AiContext.ps1
    .\Generate-AiContext.ps1 -ReposRoot D:\MyRepos
#>
param(
    [string]$ReposRoot = 'C:\Shared\PayrollEngine\Repos'
)

$ErrorActionPreference = 'Stop'

$aiContextRoot = Split-Path $PSScriptRoot -Parent
$mcpRepo       = Join-Path $ReposRoot 'PayrollEngine.Mcp.Server'
$mcpReadme     = Join-Path $mcpRepo 'README.md'
$outMcp        = Join-Path $aiContextRoot 'context\05-mcp-tools.md'

function Write-Step([string]$msg) { Write-Host "  $msg" -ForegroundColor Cyan }
function Write-Ok([string]$msg)   { Write-Host "  OK  $msg" -ForegroundColor Green }
function Write-Warn([string]$msg) { Write-Host "  WARN $msg" -ForegroundColor Yellow }

# ---------------------------------------------------------------------------
# MCP Tools -- extract from McpServer README.md
# ---------------------------------------------------------------------------
Write-Host "`n[1/1] MCP tools (README extraction)" -ForegroundColor White

if (-not (Test-Path $mcpReadme)) {
    Write-Warn "McpServer README not found at $mcpReadme - skipping"
}
else {
    $readme = Get-Content $mcpReadme -Encoding UTF8 -Raw

    $extractStart = $readme.IndexOf('## Overview')
    $extractEnd   = $readme.IndexOf('## Prerequisites')
    if ($extractStart -lt 0) { $extractStart = 0 }
    if ($extractEnd -lt 0)   { $extractEnd   = $readme.Length }

    $extracted = $readme.Substring($extractStart, $extractEnd - $extractStart).Trim()

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine('# MCP Server - Tool Inventory')
    $null = $sb.AppendLine()
    $null = $sb.AppendLine('<!-- GENERATED by Generate-AiContext.ps1 from PayrollEngine.Mcp.Server/README.md -->')
    $null = $sb.AppendLine('<!-- Do not edit manually. -->')
    $null = $sb.AppendLine()
    $null = $sb.AppendLine($extracted)

    Set-Content -Path $outMcp -Value $sb.ToString() -Encoding UTF8
    Write-Ok "Generated $outMcp"
}

Write-Host "`nDone.`n" -ForegroundColor Green
